# Generated by Codex on 2026-08-21

from django.db import migrations

WELLBEING_PERMISSIONS = {
    "wellbeing.use_wellbeing_assistant": (
        "wellbeing",
        "wellbeingassistantsettings",
        "use_wellbeing_assistant",
        "Can use wellbeing assistant",
    ),
    "wellbeing.view_own_wellbeingassistantsettings": (
        "wellbeing",
        "wellbeingassistantsettings",
        "view_own_wellbeingassistantsettings",
        "Can view own wellbeing assistant settings",
    ),
    "wellbeing.change_own_wellbeingassistantsettings": (
        "wellbeing",
        "wellbeingassistantsettings",
        "change_own_wellbeingassistantsettings",
        "Can change own wellbeing assistant settings",
    ),
}

ROLE_PERMISSION_ADDS = {
    "user": {
        "wellbeing.use_wellbeing_assistant",
        "wellbeing.view_own_wellbeingassistantsettings",
        "wellbeing.change_own_wellbeingassistantsettings",
    },
}


def sync_wellbeing_role_permissions(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    content_type_model = apps.get_model("contenttypes", "ContentType")
    permission_model = apps.get_model("auth", "Permission")
    group_model = apps.get_model("auth", "Group")

    permission_by_code = {}
    for code, (app_label, model, codename, name) in WELLBEING_PERMISSIONS.items():
        content_type, _created = content_type_model.objects.using(db_alias).get_or_create(
            app_label=app_label,
            model=model,
        )
        permission, _created = permission_model.objects.using(db_alias).get_or_create(
            content_type=content_type,
            codename=codename,
            defaults={"name": name},
        )
        permission_by_code[code] = permission

    for group_name, permission_codes in ROLE_PERMISSION_ADDS.items():
        group, _created = group_model.objects.using(db_alias).get_or_create(name=group_name)
        group.permissions.add(*(permission_by_code[code] for code in permission_codes))


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("wellbeing", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(sync_wellbeing_role_permissions, migrations.RunPython.noop),
    ]
