# Generated by Django 5.2.17 on 2026-08-07 10:29

from django.db import migrations, models

PERMISSIONS = {
    "accounts.add_user": ("user", "add_user", "Can add user"),
    "accounts.view_user": ("user", "view_user", "Can view user"),
    "accounts.change_user": ("user", "change_user", "Can change user"),
    "accounts.delete_user": ("user", "delete_user", "Can delete user"),
    "accounts.add_userprofile": ("userprofile", "add_userprofile", "Can add user profile"),
    "accounts.view_userprofile": ("userprofile", "view_userprofile", "Can view user profile"),
    "accounts.change_userprofile": (
        "userprofile",
        "change_userprofile",
        "Can change user profile",
    ),
    "accounts.delete_userprofile": (
        "userprofile",
        "delete_userprofile",
        "Can delete user profile",
    ),
    "accounts.view_own_userprofile": (
        "userprofile",
        "view_own_userprofile",
        "Can view own user profile",
    ),
    "accounts.change_own_userprofile": (
        "userprofile",
        "change_own_userprofile",
        "Can change own user profile",
    ),
    "accounts.access_support_tools": (
        "rolepermission",
        "access_support_tools",
        "Can access support tools without private user data",
    ),
    "accounts.manage_catalog_content": (
        "rolepermission",
        "manage_catalog_content",
        "Can manage nutrition catalog content",
    ),
    "accounts.administer_accounts": (
        "rolepermission",
        "administer_accounts",
        "Can administer accounts",
    ),
}

ROLE_PERMISSIONS = {
    "user": {
        "accounts.view_own_userprofile",
        "accounts.change_own_userprofile",
    },
    "support": {
        "accounts.access_support_tools",
    },
    "content_manager": {
        "accounts.manage_catalog_content",
    },
    "admin": {
        "accounts.add_user",
        "accounts.view_user",
        "accounts.change_user",
        "accounts.delete_user",
        "accounts.add_userprofile",
        "accounts.view_userprofile",
        "accounts.change_userprofile",
        "accounts.delete_userprofile",
        "accounts.access_support_tools",
        "accounts.manage_catalog_content",
        "accounts.administer_accounts",
    },
}


def seed_role_groups(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    content_type_model = apps.get_model("contenttypes", "ContentType")
    permission_model = apps.get_model("auth", "Permission")
    group_model = apps.get_model("auth", "Group")

    permission_by_code = {}
    for code, (model, codename, name) in PERMISSIONS.items():
        content_type, _created = content_type_model.objects.using(db_alias).get_or_create(
            app_label="accounts",
            model=model,
        )
        permission, _created = permission_model.objects.using(db_alias).get_or_create(
            content_type=content_type,
            codename=codename,
            defaults={"name": name},
        )
        permission_by_code[code] = permission

    for group_name, permission_codes in ROLE_PERMISSIONS.items():
        group, _created = group_model.objects.using(db_alias).get_or_create(name=group_name)
        group.permissions.set(permission_by_code[code] for code in permission_codes)


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RolePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "permissions": [
                    (
                        "access_support_tools",
                        "Can access support tools without private user data",
                    ),
                    ("manage_catalog_content", "Can manage nutrition catalog content"),
                    ("administer_accounts", "Can administer accounts"),
                ],
                "managed": False,
                "default_permissions": (),
            },
        ),
        migrations.AlterModelOptions(
            name="userprofile",
            options={
                "ordering": ["user__email"],
                "permissions": [
                    ("view_own_userprofile", "Can view own user profile"),
                    ("change_own_userprofile", "Can change own user profile"),
                ],
            },
        ),
        migrations.RunPython(seed_role_groups, migrations.RunPython.noop),
    ]
