# Generated by Django 5.2.17 on 2026-08-07 12:49

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_emailverificationtoken_passwordresettoken"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rolepermission",
            options={
                "default_permissions": (),
                "managed": False,
                "permissions": [
                    ("access_support_tools", "Can access support tools without private user data"),
                    ("manage_catalog_content", "Can manage nutrition catalog content"),
                    (
                        "view_support_admin",
                        "Can view support admin tools without private user data",
                    ),
                    ("manage_reference_data", "Can manage shared reference data"),
                    ("manage_food_catalog", "Can manage future food catalog content"),
                    ("administer_accounts", "Can administer accounts"),
                ],
            },
        ),
        migrations.CreateModel(
            name="AdminAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "source_log_entry_id",
                    models.PositiveIntegerField(blank=True, null=True, unique=True),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("addition", "Addition"),
                            ("change", "Change"),
                            ("deletion", "Deletion"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=16,
                    ),
                ),
                ("model_label", models.CharField(blank=True, max_length=120)),
                ("object_id", models.CharField(blank=True, max_length=255)),
                ("object_repr", models.CharField(blank=True, max_length=255)),
                ("change_message", models.JSONField(blank=True, default=list)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admin_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["created_at", "action"], name="accounts_ad_created_e9045c_idx"
                    ),
                    models.Index(
                        fields=["actor", "created_at"], name="accounts_ad_actor_i_0134e8_idx"
                    ),
                    models.Index(
                        fields=["model_label", "created_at"], name="accounts_ad_model_l_454439_idx"
                    ),
                ],
            },
        ),
    ]
