# Generated by Codex on 2026-08-07

from django.db import migrations

PERMISSIONS = {
    "auth.view_group": ("auth", "group", "view_group", "Can view group"),
    "auth.change_group": ("auth", "group", "change_group", "Can change group"),
    "accounts.add_user": ("accounts", "user", "add_user", "Can add user"),
    "accounts.view_user": ("accounts", "user", "view_user", "Can view user"),
    "accounts.change_user": ("accounts", "user", "change_user", "Can change user"),
    "accounts.delete_user": ("accounts", "user", "delete_user", "Can delete user"),
    "accounts.add_userprofile": (
        "accounts",
        "userprofile",
        "add_userprofile",
        "Can add user profile",
    ),
    "accounts.view_userprofile": (
        "accounts",
        "userprofile",
        "view_userprofile",
        "Can view user profile",
    ),
    "accounts.change_userprofile": (
        "accounts",
        "userprofile",
        "change_userprofile",
        "Can change user profile",
    ),
    "accounts.delete_userprofile": (
        "accounts",
        "userprofile",
        "delete_userprofile",
        "Can delete user profile",
    ),
    "accounts.view_adminauditlog": (
        "accounts",
        "adminauditlog",
        "view_adminauditlog",
        "Can view admin audit log",
    ),
    "accounts.view_own_userprofile": (
        "accounts",
        "userprofile",
        "view_own_userprofile",
        "Can view own user profile",
    ),
    "accounts.change_own_userprofile": (
        "accounts",
        "userprofile",
        "change_own_userprofile",
        "Can change own user profile",
    ),
    "accounts.access_support_tools": (
        "accounts",
        "rolepermission",
        "access_support_tools",
        "Can access support tools without private user data",
    ),
    "accounts.manage_catalog_content": (
        "accounts",
        "rolepermission",
        "manage_catalog_content",
        "Can manage nutrition catalog content",
    ),
    "accounts.view_support_admin": (
        "accounts",
        "rolepermission",
        "view_support_admin",
        "Can view support admin tools without private user data",
    ),
    "accounts.manage_reference_data": (
        "accounts",
        "rolepermission",
        "manage_reference_data",
        "Can manage shared reference data",
    ),
    "accounts.manage_food_catalog": (
        "accounts",
        "rolepermission",
        "manage_food_catalog",
        "Can manage future food catalog content",
    ),
    "accounts.administer_accounts": (
        "accounts",
        "rolepermission",
        "administer_accounts",
        "Can administer accounts",
    ),
}

ROLE_PERMISSIONS = {
    "user": {
        "accounts.view_own_userprofile",
        "accounts.change_own_userprofile",
    },
    "support": {
        "accounts.access_support_tools",
        "accounts.view_support_admin",
    },
    "content_manager": {
        "accounts.manage_catalog_content",
        "accounts.manage_reference_data",
        "accounts.manage_food_catalog",
    },
    "admin": {
        "auth.view_group",
        "auth.change_group",
        "accounts.add_user",
        "accounts.view_user",
        "accounts.change_user",
        "accounts.delete_user",
        "accounts.add_userprofile",
        "accounts.view_userprofile",
        "accounts.change_userprofile",
        "accounts.delete_userprofile",
        "accounts.view_adminauditlog",
        "accounts.access_support_tools",
        "accounts.manage_catalog_content",
        "accounts.view_support_admin",
        "accounts.manage_reference_data",
        "accounts.manage_food_catalog",
        "accounts.administer_accounts",
    },
}


def sync_role_groups(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    content_type_model = apps.get_model("contenttypes", "ContentType")
    permission_model = apps.get_model("auth", "Permission")
    group_model = apps.get_model("auth", "Group")

    permission_by_code = {}
    for code, (app_label, model, codename, name) in PERMISSIONS.items():
        content_type, _created = content_type_model.objects.using(db_alias).get_or_create(
            app_label=app_label,
            model=model,
        )
        permission, _created = permission_model.objects.using(db_alias).get_or_create(
            content_type=content_type,
            codename=codename,
            defaults={"name": name},
        )
        permission_by_code[code] = permission

    for group_name, permission_codes in ROLE_PERMISSIONS.items():
        group, _created = group_model.objects.using(db_alias).get_or_create(name=group_name)
        group.permissions.set(permission_by_code[code] for code in permission_codes)


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_rolepermission_options_adminauditlog"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.RunPython(sync_role_groups, migrations.RunPython.noop),
    ]
