# Generated by Django 5.2.17 on 2026-08-12 08:59

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_sync_admin_panel_role_permissions"),
    ]

    operations = [
        migrations.CreateModel(
            name="NutritionProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "goal",
                    models.CharField(
                        choices=[
                            ("maintain_weight", "Maintain weight"),
                            ("lose_weight", "Lose weight"),
                            ("gain_weight", "Gain weight"),
                            ("improve_habits", "Improve eating habits"),
                        ],
                        default="maintain_weight",
                        max_length=32,
                    ),
                ),
                (
                    "height_cm",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(80),
                            django.core.validators.MaxValueValidator(250),
                        ],
                    ),
                ),
                (
                    "mass_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(20),
                            django.core.validators.MaxValueValidator(400),
                        ],
                    ),
                ),
                (
                    "age_category",
                    models.CharField(
                        choices=[
                            ("under_18", "Under 18"),
                            ("18_29", "18-29"),
                            ("30_39", "30-39"),
                            ("40_49", "40-49"),
                            ("50_64", "50-64"),
                            ("65_plus", "65+"),
                            ("prefer_not_to_say", "Prefer not to say"),
                        ],
                        default="prefer_not_to_say",
                        max_length=32,
                    ),
                ),
                (
                    "activity_level",
                    models.CharField(
                        choices=[
                            ("sedentary", "Sedentary"),
                            ("light", "Light"),
                            ("moderate", "Moderate"),
                            ("active", "Active"),
                            ("very_active", "Very active"),
                        ],
                        default="moderate",
                        max_length=32,
                    ),
                ),
                (
                    "preferred_units",
                    models.CharField(
                        choices=[("metric", "Metric"), ("imperial", "Imperial")],
                        default="metric",
                        max_length=16,
                    ),
                ),
                ("dietary_preferences", models.JSONField(blank=True, default=list)),
                (
                    "consent_version",
                    models.CharField(default="nutrition_profile_mvp_v1", max_length=64),
                ),
                ("consent_granted_at", models.DateTimeField(blank=True, null=True)),
                ("consent_revoked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nutrition_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["user_id"],
                "permissions": [
                    ("view_own_nutritionprofile", "Can view own nutrition profile"),
                    ("change_own_nutritionprofile", "Can change own nutrition profile"),
                ],
            },
        ),
        migrations.CreateModel(
            name="NutritionSensitiveRestriction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "restriction_type",
                    models.CharField(
                        choices=[
                            ("allergy", "Allergy"),
                            ("intolerance", "Intolerance"),
                            ("medical_restriction", "Medical restriction"),
                        ],
                        max_length=32,
                    ),
                ),
                ("label", models.CharField(max_length=120)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "consent_version",
                    models.CharField(
                        default="nutrition_sensitive_restrictions_mvp_v1", max_length=64
                    ),
                ),
                ("consent_granted_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nutrition_sensitive_restrictions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["label", "id"],
                "permissions": [
                    (
                        "view_own_nutritionsensitiverestriction",
                        "Can view own nutrition sensitive restriction",
                    ),
                    (
                        "change_own_nutritionsensitiverestriction",
                        "Can change own nutrition sensitive restriction",
                    ),
                ],
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"], name="accounts_nu_user_id_02cc5d_idx"
                    )
                ],
            },
        ),
    ]
