# Generated by Django 5.2.17 on 2026-08-21 08:19
# ruff: noqa

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_sync_nutrition_profile_role_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rolepermission',
            options={'default_permissions': (), 'managed': False, 'permissions': [('access_support_tools', 'Can access support tools without private user data'), ('manage_catalog_content', 'Can manage nutrition catalog content'), ('view_support_admin', 'Can view support admin tools without private user data'), ('manage_reference_data', 'Can manage shared reference data'), ('manage_food_catalog', 'Can manage future food catalog content'), ('manage_fitness_catalog', 'Can manage fitness catalog content'), ('administer_accounts', 'Can administer accounts')]},
        ),
    ]
