# Generated by Django 5.2.17 on 2026-08-12 09:42

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FoodCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("slug", models.SlugField(max_length=80, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("name_ru", models.CharField(blank=True, max_length=120)),
                ("name_en", models.CharField(blank=True, max_length=120)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "food category",
                "verbose_name_plural": "food categories",
                "ordering": ["slug"],
            },
        ),
        migrations.CreateModel(
            name="FoodDataSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("code", models.SlugField(max_length=80, unique=True)),
                ("name", models.CharField(max_length=160)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("demo", "Demo"),
                            ("manual", "Manual"),
                            ("external_database", "External database"),
                        ],
                        default="manual",
                        max_length=32,
                    ),
                ),
                ("source_reference", models.CharField(blank=True, max_length=255)),
                ("license_name", models.CharField(blank=True, max_length=120)),
                ("license_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Nutrient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("code", models.SlugField(max_length=80, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("name_ru", models.CharField(blank=True, max_length=120)),
                ("name_en", models.CharField(blank=True, max_length=120)),
                ("unit", models.CharField(max_length=32)),
                (
                    "nutrient_type",
                    models.CharField(
                        choices=[
                            ("energy", "Energy"),
                            ("macronutrient", "Macronutrient"),
                            ("micronutrient", "Micronutrient"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["nutrient_type", "code"],
            },
        ),
        migrations.CreateModel(
            name="FoodItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("name_ru", models.CharField(blank=True, max_length=160)),
                ("name_en", models.CharField(blank=True, max_length=160)),
                ("synonyms", models.JSONField(blank=True, default=list)),
                (
                    "density_g_per_ml",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=6,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                ("density_metadata", models.JSONField(blank=True, default=dict)),
                ("is_verified", models.BooleanField(default=False)),
                ("source_reference", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "canonical_food",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="localized_or_alias_items",
                        to="nutrition.fooditem",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="food_items",
                        to="nutrition.foodcategory",
                    ),
                ),
                (
                    "data_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="food_items",
                        to="nutrition.fooddatasource",
                    ),
                ),
            ],
            options={
                "ordering": ["name", "id"],
            },
        ),
        migrations.CreateModel(
            name="FoodNutrient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "amount_per_100g",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                ("source_reference", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "food_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nutrient_values",
                        to="nutrition.fooditem",
                    ),
                ),
                (
                    "nutrient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="food_values",
                        to="nutrition.nutrient",
                    ),
                ),
            ],
            options={
                "ordering": ["nutrient__nutrient_type", "nutrient__code"],
            },
        ),
        migrations.AddIndex(
            model_name="fooditem",
            index=models.Index(
                django.db.models.functions.text.Lower("name"), name="nutrition_food_name_lower_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fooditem",
            index=models.Index(fields=["is_verified"], name="nutrition_food_verified_idx"),
        ),
        migrations.AddConstraint(
            model_name="foodnutrient",
            constraint=models.UniqueConstraint(
                fields=("food_item", "nutrient"), name="unique_nutrient_per_food_item"
            ),
        ),
    ]
