# Generated by Codex on 2026-08-12

from django.db import migrations

NUTRITION_MODEL_PERMISSIONS = {
    "nutrition.add_foodcategory": (
        "nutrition",
        "foodcategory",
        "add_foodcategory",
        "Can add food category",
    ),
    "nutrition.view_foodcategory": (
        "nutrition",
        "foodcategory",
        "view_foodcategory",
        "Can view food category",
    ),
    "nutrition.change_foodcategory": (
        "nutrition",
        "foodcategory",
        "change_foodcategory",
        "Can change food category",
    ),
    "nutrition.delete_foodcategory": (
        "nutrition",
        "foodcategory",
        "delete_foodcategory",
        "Can delete food category",
    ),
    "nutrition.add_fooddatasource": (
        "nutrition",
        "fooddatasource",
        "add_fooddatasource",
        "Can add food data source",
    ),
    "nutrition.view_fooddatasource": (
        "nutrition",
        "fooddatasource",
        "view_fooddatasource",
        "Can view food data source",
    ),
    "nutrition.change_fooddatasource": (
        "nutrition",
        "fooddatasource",
        "change_fooddatasource",
        "Can change food data source",
    ),
    "nutrition.delete_fooddatasource": (
        "nutrition",
        "fooddatasource",
        "delete_fooddatasource",
        "Can delete food data source",
    ),
    "nutrition.add_nutrient": ("nutrition", "nutrient", "add_nutrient", "Can add nutrient"),
    "nutrition.view_nutrient": ("nutrition", "nutrient", "view_nutrient", "Can view nutrient"),
    "nutrition.change_nutrient": (
        "nutrition",
        "nutrient",
        "change_nutrient",
        "Can change nutrient",
    ),
    "nutrition.delete_nutrient": (
        "nutrition",
        "nutrient",
        "delete_nutrient",
        "Can delete nutrient",
    ),
    "nutrition.add_fooditem": ("nutrition", "fooditem", "add_fooditem", "Can add food item"),
    "nutrition.view_fooditem": ("nutrition", "fooditem", "view_fooditem", "Can view food item"),
    "nutrition.change_fooditem": (
        "nutrition",
        "fooditem",
        "change_fooditem",
        "Can change food item",
    ),
    "nutrition.delete_fooditem": (
        "nutrition",
        "fooditem",
        "delete_fooditem",
        "Can delete food item",
    ),
    "nutrition.add_foodnutrient": (
        "nutrition",
        "foodnutrient",
        "add_foodnutrient",
        "Can add food nutrient",
    ),
    "nutrition.view_foodnutrient": (
        "nutrition",
        "foodnutrient",
        "view_foodnutrient",
        "Can view food nutrient",
    ),
    "nutrition.change_foodnutrient": (
        "nutrition",
        "foodnutrient",
        "change_foodnutrient",
        "Can change food nutrient",
    ),
    "nutrition.delete_foodnutrient": (
        "nutrition",
        "foodnutrient",
        "delete_foodnutrient",
        "Can delete food nutrient",
    ),
}


def add_nutrition_catalog_permissions(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    content_type_model = apps.get_model("contenttypes", "ContentType")
    permission_model = apps.get_model("auth", "Permission")
    group_model = apps.get_model("auth", "Group")

    permissions = []
    for app_label, model, codename, name in NUTRITION_MODEL_PERMISSIONS.values():
        content_type, _created = content_type_model.objects.using(db_alias).get_or_create(
            app_label=app_label,
            model=model,
        )
        permission, _created = permission_model.objects.using(db_alias).get_or_create(
            content_type=content_type,
            codename=codename,
            defaults={"name": name},
        )
        permissions.append(permission)

    for group_name in ("content_manager", "admin"):
        group, _created = group_model.objects.using(db_alias).get_or_create(name=group_name)
        group.permissions.add(*permissions)


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_sync_nutrition_profile_role_permissions"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("nutrition", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(add_nutrition_catalog_permissions, migrations.RunPython.noop),
    ]
