# Generated by Codex on 2026-08-12

from django.db import migrations

DIARY_PERMISSIONS = {
    "diary.view_own_meal": ("diary", "meal", "view_own_meal", "Can view own meal"),
    "diary.change_own_meal": ("diary", "meal", "change_own_meal", "Can change own meal"),
}


def add_diary_permissions(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    content_type_model = apps.get_model("contenttypes", "ContentType")
    permission_model = apps.get_model("auth", "Permission")
    group_model = apps.get_model("auth", "Group")

    permissions = []
    for app_label, model, codename, name in DIARY_PERMISSIONS.values():
        content_type, _created = content_type_model.objects.using(db_alias).get_or_create(
            app_label=app_label,
            model=model,
        )
        permission, _created = permission_model.objects.using(db_alias).get_or_create(
            content_type=content_type,
            codename=codename,
            defaults={"name": name},
        )
        permissions.append(permission)

    group, _created = group_model.objects.using(db_alias).get_or_create(name="user")
    group.permissions.add(*permissions)


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("diary", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(add_diary_permissions, migrations.RunPython.noop),
    ]
