# Generated by Django 5.2.17 on 2026-08-21 08:19
# ruff: noqa

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('name_ru', models.CharField(blank=True, max_length=160)),
                ('name_en', models.CharField(blank=True, max_length=160)),
                ('description', models.TextField(blank=True)),
                ('muscle_group', models.CharField(choices=[('full_body', 'Full body'), ('legs', 'Legs'), ('chest', 'Chest'), ('back', 'Back'), ('shoulders', 'Shoulders'), ('arms', 'Arms'), ('core', 'Core'), ('cardio', 'Cardio'), ('mobility', 'Mobility')], default='full_body', max_length=32)),
                ('movement_pattern', models.CharField(choices=[('squat', 'Squat'), ('hinge', 'Hinge'), ('push', 'Push'), ('pull', 'Pull'), ('lunge', 'Lunge'), ('core', 'Core'), ('carry', 'Carry'), ('cardio', 'Cardio'), ('mobility', 'Mobility')], default='core', max_length=32)),
                ('equipment', models.JSONField(blank=True, default=list)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('all_levels', 'All levels')], default='all_levels', max_length=32)),
                ('training_goals', models.JSONField(blank=True, default=list)),
                ('prescription_type', models.CharField(choices=[('reps', 'Reps'), ('time', 'Time')], default='reps', max_length=16)),
                ('default_duration_seconds', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', 'id'],
                'indexes': [models.Index(django.db.models.functions.text.Lower('name'), name='fit_ex_name_lower_idx'), models.Index(fields=['is_active'], name='fitness_exercise_active_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=160)),
                ('goal', models.CharField(choices=[('general_fitness', 'General fitness'), ('fat_loss', 'Fat loss'), ('muscle_gain', 'Muscle gain'), ('strength', 'Strength'), ('endurance', 'Endurance'), ('mobility', 'Mobility')], max_length=32)),
                ('experience_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=32)),
                ('duration_minutes', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(180)])),
                ('sessions_per_week', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('available_equipment', models.JSONField(blank=True, default=list)),
                ('ai_explanation', models.JSONField(blank=True, default=dict)),
                ('safety_warnings', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', 'id'],
                'permissions': [('use_ai_fitness_coach', 'Can use AI fitness coach'), ('view_own_workoutplan', 'Can view own workout plan'), ('change_own_workoutplan', 'Can change own workout plan')],
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('week_number', models.PositiveSmallIntegerField(default=1)),
                ('day_number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('title', models.CharField(max_length=160)),
                ('focus', models.CharField(blank=True, max_length=120)),
                ('estimated_duration_minutes', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(180)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='fitness.workoutplan')),
            ],
            options={
                'ordering': ['week_number', 'day_number', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('target_sets', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('target_reps_min', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('target_reps_max', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('target_duration_seconds', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rest_seconds', models.PositiveSmallIntegerField(default=60)),
                ('intensity', models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('hard', 'Hard')], default='moderate', max_length=16)),
                ('coaching_notes', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workout_prescriptions', to='fitness.exercise')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='fitness.workout')),
            ],
            options={
                'ordering': ['order', 'id'],
                'indexes': [models.Index(fields=['workout', 'exercise'], name='fitness_wex_workout_ex_idx')],
                'constraints': [models.UniqueConstraint(fields=('workout', 'order'), name='unique_exercise_order_per_workout')],
            },
        ),
        migrations.CreateModel(
            name='WorkoutLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('performed_at', models.DateTimeField()),
                ('duration_minutes', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(300)])),
                ('perceived_exertion', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1')), django.core.validators.MaxValueValidator(Decimal('10'))])),
                ('completed', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_logs', to=settings.AUTH_USER_MODEL)),
                ('workout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='fitness.workout')),
            ],
            options={
                'ordering': ['-performed_at', '-created_at'],
                'permissions': [('view_own_workoutlog', 'Can view own workout log'), ('change_own_workoutlog', 'Can change own workout log')],
                'indexes': [models.Index(fields=['user', 'performed_at'], name='fitness_log_user_time_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='workoutplan',
            index=models.Index(fields=['user', 'status'], name='fitness_plan_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='workout',
            index=models.Index(fields=['plan', 'week_number', 'day_number'], name='fitness_workout_plan_day_idx'),
        ),
        migrations.AddConstraint(
            model_name='workout',
            constraint=models.UniqueConstraint(fields=('plan', 'week_number', 'day_number', 'order'), name='unique_workout_order_per_plan_day'),
        ),
    ]
