# Generated by Codex on 2026-08-21
# ruff: noqa

from django.db import migrations

EXERCISES = (
    {
        "slug": "bodyweight_squat",
        "name": "Bodyweight squat",
        "name_ru": "Приседание с собственным весом",
        "name_en": "Bodyweight squat",
        "muscle_group": "legs",
        "movement_pattern": "squat",
        "equipment": ["bodyweight"],
        "difficulty": "beginner",
        "training_goals": ["general_fitness", "fat_loss", "muscle_gain", "strength"],
        "prescription_type": "reps",
    },
    {
        "slug": "incline_push_up",
        "name": "Incline push-up",
        "name_ru": "Отжимание от опоры",
        "name_en": "Incline push-up",
        "muscle_group": "chest",
        "movement_pattern": "push",
        "equipment": ["bodyweight"],
        "difficulty": "beginner",
        "training_goals": ["general_fitness", "fat_loss", "muscle_gain", "strength"],
        "prescription_type": "reps",
    },
    {
        "slug": "walking_lunge",
        "name": "Walking lunge",
        "name_ru": "Выпады в ходьбе",
        "name_en": "Walking lunge",
        "muscle_group": "legs",
        "movement_pattern": "lunge",
        "equipment": ["bodyweight"],
        "difficulty": "intermediate",
        "training_goals": ["general_fitness", "fat_loss", "muscle_gain", "strength"],
        "prescription_type": "reps",
    },
    {
        "slug": "jumping_jacks",
        "name": "Jumping jacks",
        "name_ru": "Прыжки jumping jacks",
        "name_en": "Jumping jacks",
        "muscle_group": "cardio",
        "movement_pattern": "cardio",
        "equipment": ["bodyweight"],
        "difficulty": "beginner",
        "training_goals": ["general_fitness", "fat_loss", "endurance"],
        "prescription_type": "time",
        "default_duration_seconds": 60,
    },
    {
        "slug": "dead_bug",
        "name": "Dead bug",
        "name_ru": "Dead bug",
        "name_en": "Dead bug",
        "muscle_group": "core",
        "movement_pattern": "core",
        "equipment": ["mat"],
        "difficulty": "beginner",
        "training_goals": ["general_fitness", "mobility", "strength"],
        "prescription_type": "reps",
    },
    {
        "slug": "plank",
        "name": "Plank",
        "name_ru": "Планка",
        "name_en": "Plank",
        "muscle_group": "core",
        "movement_pattern": "core",
        "equipment": ["mat"],
        "difficulty": "beginner",
        "training_goals": ["general_fitness", "fat_loss", "strength"],
        "prescription_type": "time",
        "default_duration_seconds": 30,
    },
    {
        "slug": "dumbbell_goblet_squat",
        "name": "Dumbbell goblet squat",
        "name_ru": "Goblet squat с гантелью",
        "name_en": "Dumbbell goblet squat",
        "muscle_group": "legs",
        "movement_pattern": "squat",
        "equipment": ["dumbbells"],
        "difficulty": "intermediate",
        "training_goals": ["general_fitness", "muscle_gain", "strength"],
        "prescription_type": "reps",
    },
    {
        "slug": "dumbbell_row",
        "name": "Dumbbell row",
        "name_ru": "Тяга гантели",
        "name_en": "Dumbbell row",
        "muscle_group": "back",
        "movement_pattern": "pull",
        "equipment": ["dumbbells"],
        "difficulty": "beginner",
        "training_goals": ["general_fitness", "muscle_gain", "strength"],
        "prescription_type": "reps",
    },
    {
        "slug": "dumbbell_floor_press",
        "name": "Dumbbell floor press",
        "name_ru": "Жим гантелей лёжа на полу",
        "name_en": "Dumbbell floor press",
        "muscle_group": "chest",
        "movement_pattern": "push",
        "equipment": ["dumbbells", "mat"],
        "difficulty": "intermediate",
        "training_goals": ["general_fitness", "muscle_gain", "strength"],
        "prescription_type": "reps",
    },
    {
        "slug": "resistance_band_pull_apart",
        "name": "Resistance band pull-apart",
        "name_ru": "Разведение эспандера",
        "name_en": "Resistance band pull-apart",
        "muscle_group": "back",
        "movement_pattern": "pull",
        "equipment": ["resistance_band"],
        "difficulty": "beginner",
        "training_goals": ["general_fitness", "mobility", "strength"],
        "prescription_type": "reps",
    },
    {
        "slug": "treadmill_walk",
        "name": "Treadmill walk",
        "name_ru": "Ходьба на дорожке",
        "name_en": "Treadmill walk",
        "muscle_group": "cardio",
        "movement_pattern": "cardio",
        "equipment": ["treadmill"],
        "difficulty": "beginner",
        "training_goals": ["general_fitness", "fat_loss", "endurance"],
        "prescription_type": "time",
        "default_duration_seconds": 300,
    },
    {
        "slug": "bike_easy_ride",
        "name": "Easy bike ride",
        "name_ru": "Лёгкая велотренировка",
        "name_en": "Easy bike ride",
        "muscle_group": "cardio",
        "movement_pattern": "cardio",
        "equipment": ["bike"],
        "difficulty": "beginner",
        "training_goals": ["general_fitness", "fat_loss", "endurance"],
        "prescription_type": "time",
        "default_duration_seconds": 300,
    },
)

PERMISSIONS = {
    "accounts.manage_fitness_catalog": (
        "accounts",
        "rolepermission",
        "manage_fitness_catalog",
        "Can manage fitness catalog content",
    ),
    "fitness.add_exercise": ("fitness", "exercise", "add_exercise", "Can add exercise"),
    "fitness.view_exercise": ("fitness", "exercise", "view_exercise", "Can view exercise"),
    "fitness.change_exercise": (
        "fitness",
        "exercise",
        "change_exercise",
        "Can change exercise",
    ),
    "fitness.delete_exercise": (
        "fitness",
        "exercise",
        "delete_exercise",
        "Can delete exercise",
    ),
    "fitness.use_ai_fitness_coach": (
        "fitness",
        "workoutplan",
        "use_ai_fitness_coach",
        "Can use AI fitness coach",
    ),
    "fitness.view_own_workoutplan": (
        "fitness",
        "workoutplan",
        "view_own_workoutplan",
        "Can view own workout plan",
    ),
    "fitness.change_own_workoutplan": (
        "fitness",
        "workoutplan",
        "change_own_workoutplan",
        "Can change own workout plan",
    ),
    "fitness.view_own_workoutlog": (
        "fitness",
        "workoutlog",
        "view_own_workoutlog",
        "Can view own workout log",
    ),
    "fitness.change_own_workoutlog": (
        "fitness",
        "workoutlog",
        "change_own_workoutlog",
        "Can change own workout log",
    ),
}

ROLE_PERMISSION_ADDS = {
    "user": {
        "fitness.use_ai_fitness_coach",
        "fitness.view_own_workoutplan",
        "fitness.change_own_workoutplan",
        "fitness.view_own_workoutlog",
        "fitness.change_own_workoutlog",
    },
    "content_manager": {
        "accounts.manage_fitness_catalog",
        "fitness.add_exercise",
        "fitness.view_exercise",
        "fitness.change_exercise",
        "fitness.delete_exercise",
    },
    "admin": {
        "accounts.manage_fitness_catalog",
        "fitness.add_exercise",
        "fitness.view_exercise",
        "fitness.change_exercise",
        "fitness.delete_exercise",
    },
}


def seed_exercises(apps, schema_editor):
    exercise_model = apps.get_model("fitness", "Exercise")
    db_alias = schema_editor.connection.alias

    for exercise_data in EXERCISES:
        exercise_model.objects.using(db_alias).update_or_create(
            slug=exercise_data["slug"],
            defaults=exercise_data,
        )


def sync_fitness_role_permissions(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    content_type_model = apps.get_model("contenttypes", "ContentType")
    permission_model = apps.get_model("auth", "Permission")
    group_model = apps.get_model("auth", "Group")

    permission_by_code = {}
    for code, (app_label, model, codename, name) in PERMISSIONS.items():
        content_type, _created = content_type_model.objects.using(db_alias).get_or_create(
            app_label=app_label,
            model=model,
        )
        permission, _created = permission_model.objects.using(db_alias).get_or_create(
            content_type=content_type,
            codename=codename,
            defaults={"name": name},
        )
        permission_by_code[code] = permission

    for group_name, permission_codes in ROLE_PERMISSION_ADDS.items():
        group, _created = group_model.objects.using(db_alias).get_or_create(name=group_name)
        group.permissions.add(*(permission_by_code[code] for code in permission_codes))


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_alter_rolepermission_options"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("fitness", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_exercises, migrations.RunPython.noop),
        migrations.RunPython(sync_fitness_role_permissions, migrations.RunPython.noop),
    ]
