# Generated by Django 5.2.17 on 2026-08-12 12:49

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodScan',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('uploaded', 'Uploaded'),
                            ('processing', 'Processing'),
                            ('failed', 'Failed'),
                            ('completed', 'Completed'),
                        ],
                        default='uploaded',
                        max_length=32,
                    ),
                ),
                ('storage_backend', models.CharField(max_length=32)),
                ('object_key', models.CharField(max_length=512, unique=True)),
                (
                    'image_format',
                    models.CharField(choices=[('JPEG', 'JPEG'), ('PNG', 'PNG')], max_length=8),
                ),
                ('content_type', models.CharField(max_length=64)),
                (
                    'uploaded_byte_size',
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    'stored_byte_size',
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    'width',
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    'height',
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ('checksum_sha256', models.CharField(max_length=64)),
                ('exif_stripped', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='food_scans',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'permissions': [
                    ('view_own_foodscan', 'Can view own food scan'),
                    ('change_own_foodscan', 'Can change own food scan'),
                ],
                'indexes': [
                    models.Index(fields=['user', 'created_at'], name='food_scan_user_created_idx'),
                    models.Index(fields=['status'], name='food_scan_status_idx'),
                ],
            },
        ),
    ]
