# Generated by Codex on 2026-08-12

from django.db import migrations

FOOD_SCAN_PERMISSIONS = {
    "food_scans.view_own_foodscan": (
        "food_scans",
        "foodscan",
        "view_own_foodscan",
        "Can view own food scan",
    ),
    "food_scans.change_own_foodscan": (
        "food_scans",
        "foodscan",
        "change_own_foodscan",
        "Can change own food scan",
    ),
}


def add_food_scan_permissions(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    content_type_model = apps.get_model("contenttypes", "ContentType")
    permission_model = apps.get_model("auth", "Permission")
    group_model = apps.get_model("auth", "Group")

    permissions = []
    for app_label, model, codename, name in FOOD_SCAN_PERMISSIONS.values():
        content_type, _created = content_type_model.objects.using(db_alias).get_or_create(
            app_label=app_label,
            model=model,
        )
        permission, _created = permission_model.objects.using(db_alias).get_or_create(
            content_type=content_type,
            codename=codename,
            defaults={"name": name},
        )
        permissions.append(permission)

    group, _created = group_model.objects.using(db_alias).get_or_create(name="user")
    group.permissions.add(*permissions)


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("food_scans", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(add_food_scan_permissions, migrations.RunPython.noop),
    ]
