# Generated by Django 5.2.17 on 2026-08-14 06:44

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def migrate_completed_status(apps, schema_editor):
    food_scan = apps.get_model("food_scans", "FoodScan")
    food_scan.objects.filter(status="completed").update(status="needs_confirmation")


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0002_sync_diary_role_permissions"),
        ("food_scans", "0002_sync_food_scan_role_permissions"),
        ("nutrition", "0002_sync_nutrition_catalog_role_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="foodscan",
            name="confirmed_meal",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="source_food_scan",
                to="diary.meal",
            ),
        ),
        migrations.AddField(
            model_name="foodscan",
            name="failure_code",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.RunPython(migrate_completed_status, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="foodscan",
            name="status",
            field=models.CharField(
                choices=[
                    ("uploaded", "Uploaded"),
                    ("processing", "Processing"),
                    ("needs_confirmation", "Needs confirmation"),
                    ("confirmed", "Confirmed"),
                    ("failed", "Failed"),
                ],
                default="uploaded",
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="FoodScanDetectedItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("label", models.CharField(max_length=160)),
                (
                    "confidence",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("1")),
                        ],
                    ),
                ),
                (
                    "estimated_mass_g",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=9,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                    ),
                ),
                ("food_name_snapshot", models.CharField(blank=True, max_length=160)),
                ("food_source_reference_snapshot", models.CharField(blank=True, max_length=255)),
                (
                    "calories_kcal",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                (
                    "protein_g",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                (
                    "fat_g",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                (
                    "carbs_g",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                ("micronutrient_snapshot", models.JSONField(blank=True, default=dict)),
                ("nutrient_snapshot", models.JSONField(blank=True, default=dict)),
                (
                    "source",
                    models.CharField(
                        choices=[("vision", "Vision"), ("manual", "Manual")],
                        default="vision",
                        max_length=32,
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                ("is_removed", models.BooleanField(default=False)),
                ("manually_corrected", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "food_scan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detected_items",
                        to="food_scans.foodscan",
                    ),
                ),
                (
                    "matched_food",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scan_detected_items",
                        to="nutrition.fooditem",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "created_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["food_scan", "is_removed"], name="scan_item_scan_removed_idx"
                    ),
                    models.Index(fields=["matched_food"], name="scan_item_food_idx"),
                ],
            },
        ),
    ]
