# Generated by Django 5.2.17 on 2026-08-14 07:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_sync_diary_role_permissions'),
        ('food_scans', '0003_foodscan_confirmed_meal_foodscan_failure_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='foodscan',
            name='analysis_attempt_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='foodscan',
            name='analysis_run_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodscan',
            name='analysis_task_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='foodscan',
            index=models.Index(fields=['analysis_run_id'], name='food_scan_analysis_run_idx'),
        ),
    ]
