# Generated by Django 5.2.17 on 2026-08-14 11:21

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food_scans", "0004_foodscan_analysis_attempt_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name='foodscandetecteditem',
            name='manual_mass_g',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=9,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AddField(
            model_name='foodscandetecteditem',
            name='portion_confidence',
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("1")),
                ],
            ),
        ),
        migrations.AddField(
            model_name='foodscandetecteditem',
            name='portion_estimated_mass_g',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=9,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AddField(
            model_name='foodscandetecteditem',
            name='portion_estimated_volume_ml',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AddField(
            model_name='foodscandetecteditem',
            name='portion_estimation_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='foodscandetecteditem',
            name='portion_estimation_method',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='foodscandetecteditem',
            name='portion_max_mass_g',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=9,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AddField(
            model_name='foodscandetecteditem',
            name='portion_min_mass_g',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=9,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
    ]
