# Generated by Codex on 2026-08-19

from django.db import migrations

AI_COACH_PERMISSIONS = {
    "ai_coach.use_ai_nutrition_coach": (
        "ai_coach",
        "aicoachsettings",
        "use_ai_nutrition_coach",
        "Can use AI nutrition coach",
    ),
    "ai_coach.view_own_aicoachsettings": (
        "ai_coach",
        "aicoachsettings",
        "view_own_aicoachsettings",
        "Can view own AI coach settings",
    ),
    "ai_coach.change_own_aicoachsettings": (
        "ai_coach",
        "aicoachsettings",
        "change_own_aicoachsettings",
        "Can change own AI coach settings",
    ),
}


def add_ai_coach_permissions(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    content_type_model = apps.get_model("contenttypes", "ContentType")
    permission_model = apps.get_model("auth", "Permission")
    group_model = apps.get_model("auth", "Group")

    permissions = []
    for app_label, model, codename, name in AI_COACH_PERMISSIONS.values():
        content_type, _created = content_type_model.objects.using(db_alias).get_or_create(
            app_label=app_label,
            model=model,
        )
        permission, _created = permission_model.objects.using(db_alias).get_or_create(
            content_type=content_type,
            codename=codename,
            defaults={"name": name},
        )
        permissions.append(permission)

    group, _created = group_model.objects.using(db_alias).get_or_create(name="user")
    group.permissions.add(*permissions)


class Migration(migrations.Migration):
    dependencies = [
        ("ai_coach", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.RunPython(add_ai_coach_permissions, migrations.RunPython.noop),
    ]
